services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RAILS_ENV: production
    volumes:
      - .:/app
    ports:
      - "80:3000"
      # - "35729:35729"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - selenium

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: app_production
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "7900:7900"

volumes:
  postgres_volume:
