services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: tatsumax123
      POSTGRES_PASSWORD: Maomaomaoti_1254
      POSTGRES_DB: app_development
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: tatsumax123
      POSTGRES_PASSWORD: Maomaomaoti_1254
      RAILS_ENV: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    tty: true 
    stdin_open: true 
    depends_on:
      - db

volumes:
  postgres_volume:
