services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b '0.0.0.0' -p 3000"
    environment:
      POSTGRES_USER: tatsumax
      POSTGRES_PASSWORD: maomaomaoti123
      RAILS_ENV: production
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      # - "35729:35729"
    tty: true 
    stdin_open: true 
    depends_on:
      - db
      
  db:
    image: postgres
    environment:
      POSTGRES_USER: tatsumax
      POSTGRES_PASSWORD: maomaomaoti123
      POSTGRES_DB: app_production
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
