FROM ruby:3.3.7

# 最新のNode.jsとYarnを公式リポジトリからインストール
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - && \
    curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | tee /etc/apt/trusted.gpg.d/yarn.asc && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update -qq && \
    apt-get install -y \
    build-essential \
    # libsqlite3-dev \
    nodejs \
    yarn \
    libpq-dev \
    # sudo \
    # curl \
    postgresql-client \
    vim

RUN git config --global alias.aa "add -A" && \
    git config --global alias.cm "commit -m" && \
    git config --global alias.s "status" && \
    git config --global alias.b "branch" && \
    git config --global user.name "tatsumax" && \
    git config --global user.email "tatsumax.development@gmail.com"

WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

# RUN bundle update --bundler
# RUN gem update --system
RUN bundle install

COPY . /app

# # entrypointの設定
# COPY entrypoint.sh /usr/bin/
# RUN chmod +x /usr/bin/entrypoint.sh
# ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000

CMD [ "rails", "server", "-b", "0.0.0.0", "-p", "3000" ]

